definitions:
  responses.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  responses.Sale:
    properties:
      buyer_document_number:
        type: string
      id:
        type: integer
      payment_id:
        type: string
      price:
        type: number
      sold_at:
        type: string
      status:
        type: string
      vehicle_id:
        type: string
    type: object
  responses.Vehicle:
    properties:
      brand:
        type: string
      color:
        type: string
      created_at:
        type: string
      id:
        type: integer
      model:
        type: string
      price:
        type: number
      updated_at:
        type: string
      vehicle_id:
        type: string
      year:
        type: integer
    type: object
  saleApi.saleWebhookRequest:
    properties:
      payment_id:
        type: string
      status:
        type: string
    type: object
  vehicleApi.buyVehicleRequest:
    properties:
      buyer_document_number:
        type: string
    required:
    - buyer_document_number
    type: object
  vehicleApi.createVehicleRequest:
    properties:
      brand:
        type: string
      color:
        type: string
      model:
        type: string
      price:
        type: number
      vehicle_id:
        type: string
      year:
        type: integer
    required:
    - brand
    - color
    - model
    - price
    - vehicle_id
    - year
    type: object
  vehicleApi.updateVehicleRequest:
    properties:
      brand:
        type: string
      color:
        type: string
      model:
        type: string
      price:
        type: number
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /sales:
    get:
      consumes:
      - application/json
      description: List sales
      parameters:
      - description: Filter sales by status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Sale'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: List sales
      tags:
      - Sale
  /sales/webhook:
    post:
      consumes:
      - application/json
      description: Sale Webhook
      parameters:
      - description: Body
        in: body
        name: expected_webhook
        required: true
        schema:
          $ref: '#/definitions/saleApi.saleWebhookRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Sale Webhook
      tags:
      - Sale
  /vehicles:
    get:
      consumes:
      - application/json
      description: Seach vehicles
      parameters:
      - description: Filter vehicles by sold status
        in: query
        name: is_sold
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Vehicle'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Search vehicles
      tags:
      - Vehicle
    post:
      consumes:
      - application/json
      description: Create vehicle
      parameters:
      - description: Body
        in: body
        name: vehicle
        required: true
        schema:
          $ref: '#/definitions/vehicleApi.createVehicleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Create Vehicle
      tags:
      - Vehicle
  /vehicles/{entity_id}:
    get:
      consumes:
      - application/json
      description: Get vehicle
      parameters:
      - description: Entity ID
        in: path
        name: entity_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get Vehicle
      tags:
      - Vehicle
    patch:
      consumes:
      - application/json
      description: Update vehicle
      parameters:
      - description: Entity ID
        in: path
        name: entity_id
        required: true
        type: string
      - description: Body
        in: body
        name: vehicle
        schema:
          $ref: '#/definitions/vehicleApi.updateVehicleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Update Vehicle
      tags:
      - Vehicle
  /vehicles/{entity_id}/buy:
    post:
      consumes:
      - application/json
      description: Buy vehicle
      parameters:
      - description: Entity ID
        in: path
        name: entity_id
        required: true
        type: string
      - description: Body
        in: body
        name: buyer_document_number
        required: true
        schema:
          $ref: '#/definitions/vehicleApi.buyVehicleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Vehicle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Buy Vehicle
      tags:
      - Vehicle
swagger: "2.0"
