services:
  mongo:
    image: mongo:latest
    container_name: mongo-vehicle-platform-sales
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
