services:
  postgres:
    image: postgres:latest
    container_name: postgres-vehicle-platform-sales
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: vehicle-platform-sales
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network

  migrate:
    image: migrate/migrate:latest
    container_name: migrations-vehicle-platform-sales
    depends_on:
      - postgres
    volumes:
      - ./db/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://docker:docker@postgres:5432/vehicle-platform-sales?sslmode=disable",
      "up"
    ]
    networks:
      - shared_network

  vehicle-platform-sales:
    build: .
    container_name: api-vehicle-platform-sales
    restart: always
    depends_on:
      - postgres
      - migrate
    ports:
      - "4002:4002"
    environment:
      API_PORT: "4002"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "docker"
      DB_PASSWORD: "docker"
      DB_NAME: "vehicle-platform-sales"
      VEHICLE_PLATFORM_PAYMENTS_HOST: "http://vehicle-platform-payments:4003"
      VEHICLE_PLATFORM_SALES_HOST: "http://vehicle-platform-sales:4002"
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: true
